messages:
  add: "Вы выдали {elo} рейтинга игроку {player}" # Сообщение при выдаче рейтинга
  remove: "Вы забрали {elo} рейтинга у игрока {player}" # Сообщение при снятии рейтинга
  info: "У игрока {player} {elo} рейтинга" # Сообщение статистики игрока
  lost: "Вы потеряли {elo} рейтинга" # Когда потерял ело
  received: "Вы получили {elo} рейтинга" # Когда получил ело
  reload: "Конфиг успешно перезагружен" # Когда плагин перезагружен
  noPerm: "У вас нет прав"
  number: "Некорректное число"
  offline: "Игрок должен быть онлайн!"
  set: "Вы установили {elo} рейтинга игроку {player}"
  help:
    - "Использование:"
    - "/aelo set ник кол-во - устанавливает рейтинг"
    - "/aelo add ник кол-во - добавляет рейтинг"
    - "/aelo remove ник кол-во - уменьшает рейтинг"
    - "/aelo info ник - просмотр рейтинга игрока"
    - "/aelo reload - перезагрузка конфига"
elo:
  main:
    perKill: 10-20 # Диапазон того, сколько будет добавлено игроку при убийстве другого игрока
    perDeath: 1-5 # Диапазон того, сколько будет снято рейтинга при смерти от игрока
  negative:
    color: "&#FF001F" # Цвет для отрицательного числа
  neutral:
    color: "&#968385" # Цвет когда рейтинг равен нулю
  positive:
    color: "&#40EA11" # Цвет для положительного числа